name: Create Sentry Release

on:
  push:
    branches:
      - main  # Sesuaikan dengan nama branch utama Anda

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Sentry CLI
        run: |
          curl -sL https://sentry.io/get-cli/ | bash

      - name: Set up Sentry release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          export SENTRY_ORG=syuaib
          export SENTRY_PROJECT=absen-siswa
          export VERSION=$(sentry-cli releases propose-version)

          sentry-cli releases new "$VERSION"
          sentry-cli releases set-commits "$VERSION" --auto
          sentry-cli releases finalize "$VERSION"
